# Site settings
email: dbsgapsl93@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: hyemin.Yoon
description: 
url: "https://yoonhyemin.github.io/"
twitter_username:
default_img:

# Profile settings
name: 'Yoonhyemin'
profile_img: 
profile: 'Developer - Application / web / big data Analyst'
social: 
  github: 'https://github.com/yoonhyemin'

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

