# Site settings
email: 'dbsgpals93@gmail.com'
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: hyemin.Yoon
description: 
url: "https://yoonhyemin.github.io/"
twitter_username:
default_img:

# Profile settings
name: 'Yoonhyemin'
profile_img: 'https://github.com/yoonhyemin/yoonhyemin.github.io/raw/master/img/me.jpg'
profile: 'Developer - Application / web / big data Analyst'
social: 'https://www.instagram.com/hyeminny_'
  github: 'https://github.com/yoonhyemin'

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
