# Site settings
email: kjh338076@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: junhee.ko
description: running and running
url: "https://kojunhee.github.io/"
twitter_username:
default_img:

# Profile settings
name: 'KoJunHee'
profile_img: 'https://avatars2.githubusercontent.com/u/24292263?s=400&u=26abd8f348a147b7741cba262db0609a6fe8178f&v=4'
profile: 'Developer - android front / web server'
social:
  github: 'https://github.com/kojunhee'

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

